GCC = gcc -Wall 

ex1: ex1.c
	${GCC} ex1.c -o ex1 
	./ex1

ex2: ex2.c
	${GCC} ex2.c -o ex2 
	./ex2

ex3: ex3.c
	${GCC}  ex3.c -o ex3 -lm
	./ex3 abc

ex4: ex4.c
	${GCC} ex4.c -o ex4
	./ex4

ex5:
	${GCC} ex5.c -o ex5
	./ex5


clean: 
	rm ex1 ex2 ex3 ex4 ex5