
run:
	javac EX1/*.java \
	javac EX2/*.java \
	javac EX3/*.java \
	javac EX4/*.java \
	javac EX5/*.java \

clean:
	rm EX1/*.class \
	rm EX2/*.class \
	rm EX3/*.class \
	rm EX4/*.class \
	rm EX5/*.class \


 