
EXE = program



GCC = gcc -Wall
OPTIONS = -Wall

ex1:
	${GCC} ex1.c -o ex1 
	./ex1

ex2:
	${GCC} ex2.c -o ex2 
	./ex2 1 1

ex3:
	${GCC} ex3.c -o ex3
	./ex3 10

ex4:
	${GCC} ex4.c -o ex4
	./ex4

ex5:
	${GCC} ex5.c -o ex5
	./ex5


